version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8876:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./.:/var/www/public/
    container_name: app_nginx
    depends_on:
      - php
  php:
    image: php:fpm
    depends_on:
      - db
    volumes:
      - ./:/var/www/public
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
